# Jykell configuration
#markdown: redcarpet
#highlighter: pygments
markdown: kramdown
highlighter: rouge
paginate: 5
language: 'en-uk'

# Website info
name: Android修行
description: ——LuckyTurbo

# Author's info
author: LuckyTurbo
# edit 'categories' in the front matter of every post to match this username
nickname: LuckyTurbo
bio: 非科班出生的Android开发者，在这科技爆棚的今天，有幸混口饭吃，在此耕耘，望有天能进入BAT.
location: 苏州, China
url: 'http://yuanyang5917.github.io/'
image: 'assets/images/LuckyTurboHead.gif'

short_url: 'yuanyang5917.github.io/'
google_analytics: UA-69281367-1
disqus: username
# edit baseurl to simply '/' if using as your personal page (instead of a project page)
baseurl: 

# Permalinks
permalink: /:title
# permalink: /author/:username
# permalink: /tag/:tag


# gems and other configs
gems: [jekyll-paginate]
exclude: [vendor]

# Additional settings available on the front-matter
# Site logo in the index.html (as in demo.ghost.io)
# Author's page cover in _layouts/author.html
# The same for page.html and tag.html layouts
# Post's page cover as a per-post basis _posts/...
# Disqus comments as a per-post basis
# ...


# Settings for builing master branch with travis-ci
# with jekyll-travis

# Settings for deploy rake task
# Username and repo of Github repo, e.g.
# https://github.com/USERNAME/REPO.git
# username defaults to ENV['GIT_NAME'] used by Travis
# repo defaults to USERNAME.github.io
# Branch defaults to "source" for USERNAME.github.io
# or "master" otherwise
safe: false
lsi: false
username: yuanyang5917
repo: yuanyang5917.github.io
branch: master
relative_source: ../yuanyang5917.github.io/
destination: ../yuanyang5917.github.io-pages/
production_url:  https://yuanyang5917.github.io
source_url:      https://github.com/yuanyang5917/yuanyang5917.github.io/

exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml
